### ISSUE TITLE
すごいコードだ！！

### ISSUE THREAD

**Issue by c0b21057** [KasuyaRen/ProjExD#2]
https://github.com/KasuyaRen/ProjExD/blob/79f11e147b0fae8b7943c48895e0f48a9568bd1e/ex01/alphabet.py#L56エラーが起きて時間がなかった中よくがんばったね。僕と君とは一年半前この大学で出会った。以下略

**Comment by KasuyaRen** [comment]
とても感銘を受けましたありがとう！
