### ISSUE TITLE
持ってない勢

### ISSUE THREAD

**Issue by Ichii0924** [KasuyaRen/ProjExD#4]
https://github.com/KasuyaRen/ProjExD/blob/143925218b5513adf81770d9c86d5cc1aaf1533f/ex02/calc.py#L49

＝で右クリの全削除はできるけど、私みたいにノートパソコンでマウス使わない人はホイールクリックできないから、一文字削除できない。コードは変えてもいいと思います。あといいピンク色です

**Comment by KasuyaRen** [comment]
貴重なご意見ありがとうございます。確かにマウスを常に持っていない人間がいるなんて想定していなかったので、早く買ってほしいものですね。マウスホイールクリックだけでなくダブルクリックでも同じようになるよう修正しました。
